### PR TITLE
feat(bounty): add empty state when it's a internal chrome page

### PR DESCRIPTION
**Pull request by crocodile-bounty-hunter**
### Related to

Bounty Hunter Challenge

### Context

Add a new state in the Extension when the user is on an "internal" Chrome page, for example, `chrome://new-tab-page`.

image

### CODE REVIEW

**Review by crocodile-bounty-hunter — COMMENTED** [review]
updated loading state

**Review by ricardofelgueiras — APPROVED** [review]

**Comment by ricardofelgueiras** [comment]
Thank you for your contribution @crocodile-bounty-hunter. 

Can you match this style?
image

Thanks in advance.

**Comment by crocodile-bounty-hunter** [comment]
> Thank you for your contribution @crocodile-bounty-hunter.

Sure @ricardofelgueiras, I hope it match with the requirements :)

**Comment by ricardofelgueiras** [comment]
@crocodile-bounty-hunter thank you once more for your contribution.

Once you solved one of the [bounties](https://github.com/rows/X/?tab=readme-ov-file#open-bounties-program), you're entitled to a 20$ reward. For us to proceed with the payment, please send me your details to ricardo@rows.com.

Thanks.

**Pull request merged**
